spring:
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mvc:
    view:
      suffix: .html
    static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/templates/, classpath:/static/

      #
          #  classpath:/META-INF/resources/"
          #
          #  "classpath:/resources/"
          #
          #  "classpath:/static/"
          #
          #  "classpath:/public/"
          #
          #  spring.resources.static-locations=classpath:/coding/,classpath:/kuang/
          #

